-- Alimentation des tales

INSERT INTO product (product_category, brand, product_name, price)
VALUES
    ('Phone', 'Samsung', 'Galaxy S20', 999),
    ('Phone', 'OnePlus', 'OnePlus Nord', 499),
    ('Phone', 'Microsoft', 'Surface Duo', 1399),
    ('Phone', 'Apple', 'iPhone 12 Pro', 1099),
    ('Phone', 'Dell', 'Dell XPS 13', 1299),
    ('Laptop', 'Samsung', 'Galaxy Book Flex', 1299),
    ('Laptop', 'Microsoft', 'Surface Laptop 3', 999),
    ('Laptop', 'Apple', 'MacBook Air', 999),
    ('Laptop', 'Dell', 'Dell Inspiron 15', 599),
    ('Phone', 'Samsung', 'Galaxy Note 20 Ultra', 1299),
    ('Phone', 'OnePlus', 'OnePlus 8T', 749),
    ('Phone', 'Microsoft', 'Surface Pro 7', 899),
    ('Phone', 'Apple', 'iPhone SE', 399),
    ('Phone', 'Dell', 'Dell XPS 15', 1499),
    ('Laptop', 'Samsung', 'Galaxy Chromebook', 999),
    ('Laptop', 'Microsoft', 'Surface Book 3', 1399),
    ('Laptop', 'Apple', 'MacBook Pro 13', 1299),
    ('Laptop', 'Dell', 'Dell Latitude 14', 899),
    ('Phone', 'Samsung', 'Galaxy Z Fold 2', 1999),
    ('Phone', 'OnePlus', 'OnePlus 9', 899),
    ('Phone', 'Microsoft', 'Surface Go 2', 399),
    ('Phone', 'Apple', 'iPhone 11', 699),
    ('Phone', 'Dell', 'Dell Alienware 15', 1499),
    ('Laptop', 'Samsung', 'Galaxy Book S', 999),
    ('Laptop', 'Microsoft', 'Surface Laptop Go', 549),
    ('Laptop', 'Apple', 'MacBook Pro 16', 2399),
    ('Laptop', 'Dell', 'Dell Precision 15', 1799),
    ('Phone', 'Samsung', 'Galaxy A71', 399),
    ('Phone', 'OnePlus', 'OnePlus Nord N10', 299),
    ('Phone', 'Microsoft', 'Surface Duo 2', 1599),
    ('Phone', 'Apple', 'iPhone 13', 799),
    ('Phone', 'Dell', 'Dell XPS 17', 2299),
    ('Laptop', 'Samsung', 'Galaxy Book Pro', 1199),
    ('Laptop', 'Microsoft', 'Surface Laptop Studio', 1599),
    ('Laptop', 'Apple', 'MacBook Air M1', 1299),
    ('Laptop', 'Dell', 'Dell Inspiron 13', 799),
    ('Phone', 'Samsung', 'Galaxy Z Flip 3', 999),
    ('Phone', 'OnePlus', 'OnePlus 9 Pro', 999),
    ('Phone', 'Microsoft', 'Surface Pro X', 899),
    ('Phone', 'Apple', 'iPhone 13 Pro', 999),
    ('Phone', 'Dell', 'Dell G15', 1299),
    ('Laptop', 'Samsung', 'Galaxy Book Pro 360', 1399),
    ('Laptop', 'Microsoft', 'Surface Laptop 4', 1199),
    ('Laptop', 'Apple', 'MacBook Pro 14', 1999),
    ('Laptop', 'Dell', 'Dell XPS 14', 1899),
    ('Phone', 'Samsung', 'Galaxy A52', 349),
    ('Phone', 'OnePlus', 'OnePlus 8 Pro', 899),
    ('Phone', 'Microsoft', 'Surface Duo 3', 1899),
    ('Phone', 'Apple', 'iPhone 13 Mini', 699),
    ('Phone', 'Dell', 'Dell XPS 12', 1699);
